### ISSUE TITLE
Orleans 1.5 compatible release?

### ISSUE THREAD

**Issue by cata** [OrleansContrib/Orleans.StorageProvider.Redis#13]
Hi guys, 

I've noticed that the changes required for Orleans 1.5 compatibility are in. Would it be possible to release a corresponding Nuget package? We can of course build a package ourselves, but hey, getting it from Nuget would be preferable.

Thanks!

**Comment by normanhh3** [comment]
Looks like the AppVeyor update for the NuGet package is failing for some reason.
