### ISSUE TITLE
Fix CI builds

### ISSUE THREAD

**Issue by martinothamar** [OrleansContrib/Orleans.StorageProvider.Redis#21]
Builds are broken and no nupkgs are published. Looking to use this in a couple of projects so would be very happy if someone took the time to fix the CI stuff

**Comment by galvesribeiro** [comment]
@richorama do you still own that package? If you prefer, I can create a new packageId which would represent the new packages for v2 upward and make the CI to work again.

**Comment by martinothamar** [comment]
Yeah the package id should probably change any, so that is shows up here when searching for Orleans.Persistence: [https://www.nuget.org/packages?q=Orleans.Persistence](https://www.nuget.org/packages?q=Orleans.Persistence)

**Comment by galvesribeiro** [comment]
Sure, lets wait for @richorama reply and take a direction.

**Comment by richorama** [comment]
Sorry guys, been maxed out with other stuff. 

I think the package identity was passed over to me but I'll check.

**Comment by jmvermeulen** [comment]
Any update on this? Would be great to have a formal release of this nuget.

**Comment by amccool** [comment]
working #27
