### ISSUE TITLE
What is the license for this software?

### ISSUE THREAD

**Issue by richorama** [OrleansContrib/Orleans.StorageProvider.Redis#6]
MIT?

**Comment by amccool** [comment]
StackExchange.Redis package is Copyright Stack Exchange inc. 2014
Newtonsoft.json package is The MIT License (MIT)

I'm not familiar with the Stack Exchange licensing

**Comment by amccool** [comment]
https://raw.githubusercontent.com/StackExchange/StackExchange.Redis/master/LICENSE
appears to be MIT with some 3rd party nuances

**Comment by richorama** [comment]
Let's make this MIT.
